import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import user from "./Components/Info.json";
import Header from "./Components/Header/Header";

export default function Home() {
  const [mode, setMode] = useState(false);

  return (
    <div
      className={mode === false ? styles.container : styles.container__light}
    >
      <Head>
        <title>Switch Master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={mode === false ? styles.topBG : styles.topBG__light}>
        <Header setMode={setMode} mode={mode} />
        <>
          <div className={styles.cards}>
            {user &&
              user.user.map((e) => (
                <div
                  key={e.followers}
                  className={mode === false ? styles.card : styles.card__light}
                >
                  {e.socialMedia === "facebook" ? (
                    <span className={styles.facebook}></span>
                  ) : e.socialMedia === "twitter" ? (
                    <span className={styles.twitter}></span>
                  ) : e.socialMedia === "instagram" ? (
                    <span className={styles.instagram}></span>
                  ) : e.socialMedia === "youtube" ? (
                    <span className={styles.youtube}></span>
                  ) : null}
                  <h4>
                    {e.socialMedia === "facebook" ? (
                      <Image
                        src="/images/icon-facebook.svg"
                        width={20}
                        height={20}
                      />
                    ) : e.socialMedia === "twitter" ? (
                      <Image
                        src="/images/icon-twitter.svg"
                        width={20}
                        height={20}
                      />
                    ) : e.socialMedia === "instagram" ? (
                      <Image
                        src="/images/icon-instagram.svg"
                        width={20}
                        height={20}
                      />
                    ) : e.socialMedia ? (
                      <Image
                        src="/images/icon-youtube.svg"
                        width={20}
                        height={20}
                      />
                    ) : null}
                    {e.userName}
                  </h4>
                  <h1>{e.followers}</h1>
                  <h2>{e.type}</h2>
                  {e.lastUpdate === "up" ? (
                    <h3 className={styles.up}>
                      <Image src="/images/icon-up.svg" width={8} height={4} />
                      {e.lastFollowers}
                      Today
                    </h3>
                  ) : (
                    <h3 className={styles.down}>
                      <Image src="/images/icon-down.svg" width={8} height={4} />
                      {e.lastFollowers} Today
                    </h3>
                  )}
                </div>
              ))}
          </div>
          <div
            className={
              mode === false
                ? styles.overview__container
                : styles.overview__container__light
            }
          >
            <h1
              className={
                mode === false
                  ? styles.overview__title
                  : styles.overview__title__light
              }
            >
              Overview - Today
            </h1>
            <div
              className={
                mode === false
                  ? styles.overview__cards
                  : styles.overview__cards__light
              }
            >
              {user &&
                user.Overview.map((e, i) => (
                  <div
                    key={e.number}
                    className={
                      mode === false
                        ? styles.overview__card
                        : styles.overview__card__light
                    }
                  >
                    <div
                      className={
                        mode === false
                          ? styles.overview__card__top
                          : styles.overview__card__top__light
                      }
                    >
                      <h4>{e.type}</h4>{" "}
                      <Image src={e.icon} width={20} height={20} />
                    </div>
                    <div
                      className={
                        mode === false
                          ? styles.overview__card__bottom
                          : styles.overview__card__bottom__light
                      }
                    >
                      <h1>{e.number}</h1>
                      {e.lastUpdate === "up" ? (
                        <h4 className={styles.up}>
                          <Image
                            src="/images/icon-up.svg"
                            width={8}
                            height={4}
                          />
                          {e.percent}%
                        </h4>
                      ) : (
                        <h4 className={styles.down}>
                          <Image
                            src="/images/icon-down.svg"
                            width={8}
                            height={4}
                          />
                          {e.percent}%
                        </h4>
                      )}
                    </div>
                  </div>
                ))}
            </div>
          </div>
        </>
      </div>
    </div>
  );
}
