import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/LigthMode.module.css";
import user from "../Info.json";

export default function Home({ setMode }) {
  const onLigthMode = (e) => {
    if (e.target.value === "on") {
      setMode(true);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.topBG}>
        <header className={styles.header}>
          <div className={styles.header__title}>
            <h1>Social Media Dashboard</h1>
            <h5>Total Followers: 23,004</h5>
          </div>
          <div className={styles.line}></div>
          <div className={styles.header__toggle}>
            <h4>Dark Mode</h4>
            <label className={styles.switch}>
              <input type="checkbox" onClick={onLigthMode} checked />
              <span className={styles.slider}></span>
            </label>
          </div>
        </header>
        <div className={styles.cards}>
          {user &&
            user.user.map((e, i) => (
              <div key={i} className={styles.card}>
                {e.socialMedia === "facebook" ? (
                  <span className={styles.facebook}></span>
                ) : e.socialMedia === "twitter" ? (
                  <span className={styles.twitter}></span>
                ) : e.socialMedia === "instagram" ? (
                  <span className={styles.instagram}></span>
                ) : e.socialMedia === "youtube" ? (
                  <span className={styles.youtube}></span>
                ) : null}
                <h4>
                  {e.socialMedia === "facebook" ? (
                    <Image
                      src="/images/icon-facebook.svg"
                      width={20}
                      height={20}
                    />
                  ) : e.socialMedia === "twitter" ? (
                    <Image
                      src="/images/icon-twitter.svg"
                      width={20}
                      height={20}
                    />
                  ) : e.socialMedia === "instagram" ? (
                    <Image
                      src="/images/icon-instagram.svg"
                      width={20}
                      height={20}
                    />
                  ) : e.socialMedia ? (
                    <Image
                      src="/images/icon-youtube.svg"
                      width={20}
                      height={20}
                    />
                  ) : null}
                  {e.userName}
                </h4>
                <h1>{e.followers}</h1>
                <h2>{e.type}</h2>
                {e.lastUpdate === "up" ? (
                  <h3 className={styles.up}>
                    <Image src="/images/icon-up.svg" width={8} height={4} />
                    {e.lastFollowers}
                    Today
                  </h3>
                ) : (
                  <h3 className={styles.down}>
                    <Image src="/images/icon-down.svg" width={8} height={4} />
                    {e.lastFollowers} Today
                  </h3>
                )}
              </div>
            ))}
        </div>
        <div className={styles.overview__container}>
          <h1 className={styles.overview__title}>Overview - Today</h1>
          <div className={styles.overview__cards}>
            {user &&
              user.Overview.map((e, i) => (
                <div key={i} className={styles.overview__card}>
                  <div className={styles.overview__card__top}>
                    <h4>{e.type}</h4>{" "}
                    <Image src={e.icon} width={20} height={20} />
                  </div>
                  <div className={styles.overview__card__bottom}>
                    <h1>{e.number}</h1>
                    {e.lastUpdate === "up" ? (
                      <h4 className={styles.up}>
                        <Image src="/images/icon-up.svg" width={8} height={4} />
                        {e.percent}%
                      </h4>
                    ) : (
                      <h4 className={styles.down}>
                        <Image
                          src="/images/icon-down.svg"
                          width={8}
                          height={4}
                        />
                        {e.percent}%
                      </h4>
                    )}
                  </div>
                </div>
              ))}
          </div>
        </div>
      </div>
    </div>
  );
}
